 for($i = 1; $i -lt 2; $i++)
 { start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-1/IntroToJava.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-2/IntroToJava.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-3/JavaChapter1.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-4/JavaChapter1.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-5/JavaChapter1.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-6/JavaChapter1.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-7/JavaChapter1PracticeSet.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-8/Chapter2.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-9/Chapter2.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-10/Chapter2.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-12/Ch2_Practice.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-13/Ch3Strings.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-14/Ch3Strings.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-16/ch4conditional.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-17/ch4conditional.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-18/ch4conditional.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-19/ch4practiceset.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-21/Chapter_5.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-22/Chapter_5.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-22/Chapter_5_pPwkFbw.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-23/Chapter_5.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-24/Chapter_5.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-25/Chapter_5__Practice_Set.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-26/Chapter_6_Arrays.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-27/Chapter_6_Arrays.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-28/Chapter_6_Arrays.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-29/Chapter_6_Practice_Set.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-31/Ch7.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-32/Ch7.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-33/Ch7.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-34/Ch7.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-35/Chapter7_PracticeSet.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-35/UltimateJavaCheatSheet_9WOjYHf.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-35/UltimateJavaCheatSheet_oRsYgeN.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-36/Ch8.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-37/Ch8.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-38/Ch8.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-38/Ch8_5klViN2.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-38/Ch8_I197TmM.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-39/Ch8_PS.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-40/Chapter9.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-42/Chapter9.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-44/Ch9PS.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-45/Chapter10.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-46/JavaChapter10.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-47/JavaChapter10.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-48/JavaChapter10.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-49/JavaChapter10.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-52/JavaChapter10PracticeSet.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-53/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-54/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-55/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-56/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-57/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-58/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-59/JavaChapter11AbstractClasses.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-60/Chapter11PS.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-62/ch12notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-63/ch12notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-64/ch12notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-65/ch12notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-66/ch12notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-67/Ch12psJava.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-69/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-70/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-71/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-72/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-73/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-74/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-75/Ch13Java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-76/Chapter13PracticeSetJava.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-78/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-79/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-80/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-81/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-82/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-83/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-84/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-85/Ch14_java.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-86/Ch14PS.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-101/ch15advjava.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-102/ch15javaps.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-105/AdvancedJava2Notes.pdf'; Start-sleep 6
start Firefox 'https://api.codewithharry.com/media/videoSeriesFiles/courseFiles/java-tutorials-for-beginners-111/AdvancedJava2Notes.pdf'; Start-sleep 6
}